name: Deploy

on:
  push:
    branches:
      - production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Setup Environment Variables
        run: echo "ARCHIVE_NAME=production_output_$(date +%s).tar.gz" >> $GITHUB_ENV

      - name: Archive Built Output
        run: tar -czf ${{ env.ARCHIVE_NAME }} .output

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
          body: "Production build artifacts"
          files: ${{ env.ARCHIVE_NAME }}
          allow_empty_upload: true
